package problem1;

public enum ErrorType {
  INSUFFICIENT_ARGS,
  EMAIL_ERROR,
  EMAIL_TEMPLATE_MISSING_ERROR,
  LETTER_ERROR,
  LETTER_TEMPLATE_MISSING_ERROR,
  OUTPUT_DIR_ERROR,
  CSV_FILE_ERROR,
  VALID

}
